
const {ccclass, property} = cc._decorator;

@ccclass
export default class GameData {
    // 锅皮肤
    public pot:Array<object> =[
        {
            name:"default",
            bigArm:'resources/action/default/arm1.png',
            lowerArm:'resources/action/default/arm2.png',
            hand:'resources/action/default/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"10",
            bigArm:'resources/action/10/arm1.png',
            lowerArm:'resources/action/10/arm2.png',
            hand:'resources/action/10/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"1",
            bigArm:'resources/action/1/arm1.png',
            lowerArm:'resources/action/1/arm2.png',
            hand:'resources/action/1/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"2",
            bigArm:'resources/action/2/arm1.png',
            lowerArm:'resources/action/2/arm2.png',
            hand:'resources/action/2/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"3",
            bigArm:'resources/action/3/arm1.png',
            lowerArm:'resources/action/3/arm2.png',
            hand:'resources/action/3/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"4",
            bigArm:'resources/action/4/arm1.png',
            lowerArm:'resources/action/4/arm2.png',
            hand:'resources/action/4/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"5",
            bigArm:'resources/action/5/arm1.png',
            lowerArm:'resources/action/5/arm2.png',
            hand:'resources/action/5/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"6",
            bigArm:'resources/action/6/arm1.png',
            lowerArm:'resources/action/6/arm2.png',
            hand:'resources/action/6/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"7",
            bigArm:'resources/action/7/arm1.png',
            lowerArm:'resources/action/7/arm2.png',
            hand:'resources/action/7/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"8",
            bigArm:'resources/action/8/arm1.png',
            lowerArm:'resources/action/8/arm2.png',
            hand:'resources/action/8/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"9",
            bigArm:'resources/action/9/arm1.png',
            lowerArm:'resources/action/9/arm2.png',
            hand:'resources/action/9/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"11",
            bigArm:'resources/action/11/arm1.png',
            lowerArm:'resources/action/11/arm2.png',
            hand:'resources/action/11/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
        {
            name:"12",
            bigArm:'resources/action/12/arm1.png',
            lowerArm:'resources/action/12/arm2.png',
            hand:'resources/action/12/hand_b.png',
            price:70,
            vdata:[{"x":0,"y":0,"w":152,"h":324,"sx":1,"sy":1,"r":0},{"x":-3,"y":-16,"w":143,"h":206,"sx":1,"sy":1,"r":33},{"x":124,"y":0,"w":541,"h":114,"sx":1,"sy":1,"r":0}],
        },
    ];
    // 饼皮肤
    public cake:Array<object> =[
        {
            name:"default",
            pancake:'resources/action/default/pancake.png',
            price:30,
        },
        {
            name:"10",
            pancake:'resources/action/10/pancake.png',
            price:30,
        },
        {
            name:"1",
            pancake:'resources/action/1/pancake.png',
            price:30,
        },
        {
            name:"2",
            pancake:'resources/action/2/pancake.png',
            price:30,
        },
        {
            name:"3",
            pancake:'resources/action/3/pancake.png',
            price:30,
        },
        {
            name:"4",
            pancake:'resources/action/4/pancake.png',
            price:30,
        },
        {
            name:"5",
            pancake:'resources/action/5/pancake.png',
            price:30,
        },
        {
            name:"6",
            pancake:'resources/action/6/pancake.png',
            price:30,
        },
        {
            name:"7",
            pancake:'resources/action/7/pancake.png',
            price:30,
        },
        {
            name:"8",
            pancake:'resources/action/8/pancake.png',
            price:30,
        },
        {
            name:"9",
            pancake:'resources/action/9/pancake.png',
            price:30,
        },
        {
            name:"11",
            pancake:'resources/action/11/pancake.png',
            price:30,
        },
        {
            name:"12",
            pancake:'resources/action/12/pancake.png',
            price:30,
        },
    ];
}
